oss-fuzz: Fix fuzzer flags in CFLAGS.
When running fuzzer locally by doing
 $ ./configure CC=clang CFLAGS="-g -O2 -fsanitize=fuzzer-no-link -Werror"
 $ make oss-fuzz-targets
fails due to "(.text+0x20): undefined reference to `main'"

The patch fixes it by replacing "fuzzer-no-link" to "fuzzer" so the
binary under tests/oss-fuzz/ can be generated.

Cc: Bhargava Shastry <bshastry@sect.tu-berlin.de>
Cc: Yifeng Sun <pkusunyifeng@gmail.com>
Signed-off-by: William Tu <u9012063@gmail.com>